Writable:
  LogLevel: "INFO"
  StoreAndForward:
    Enabled: false

  Pipeline:
    ExecutionOrder: "HTTPExport"

    Functions:
      FilterByProfileName:
        Parameters:
          ProfileNames: ""
          FilterOut: "false"
      FilterByDeviceName:
        Parameters:
          DeviceNames: ""
          FilterOut: "false"
      FilterBySourceName:
        Parameters:
          SourceNames: ""
          FilterOut: "false"
      FilterByResourceName:
        Parameters:
          ResourceNames: ""
          FilterOut: "false"
      Transform:
        Parameters:
          Type: "json"
      Compress:
        Parameters:
          Algorithm: "gzip"
      Encrypt:
        Parameters:
          Algorithm: "aes256"
          SecretName: "aes"
          SecretValueKey: "key"
      Batch:
        Parameters:
          Mode: "bytimecount" # can be "bycount", "bytime" or "bytimecount"
          BatchThreshold: "30"
          TimeInterval: "60s"
          MergeOnSend: "false"
      AddTags:
        Parameters:
          Tags: ""
      HTTPExport:
        Parameters:
          Method: "post"
          MimeType: "application/json"
          # Url can have place holders in the form "{key-name}" that are replaced with matching Context values. Error occurs if no value match place holder(s).
          Url: "<put your URL here>"
          PersistOnError: "false"
          ContinueOnSendError: "false" # For chained multi destination exports, if true continues after send error so next export function executes.
          ReturnInputData: "false"  # For chained multi destination exports if true, passes the input data to next export function.
          HeaderName: "" # Name of the header key to add to the HTTP header
          SecretValueKey: "" # The key of the secret stored in the SecretStore
          SecretName: "" # The name of the secret in the SecretStore
      # Partial name matching allows multiple instances of same function (configured differently) to be in the function pipeline.
      # This supports chaining export functions to export to multiple destinations. Name must start with name that matches built in function.
      HTTPExport2:
        Parameters:
          Method: "post"
          MimeType: "application/json"
          # Url can have place holders in the form "{key-name}" that are replaced with matching Context values. Error occurs if no value match place holder(s).
          Url: "<put your URL here>"
          PersistOnError: "false"
          ContinueOnSendError: "false" # For chained multi destination exports, if true continues after send error so next export function executes.
          ReturnInputData: "false"  # For chained multi destination exports if true, passing the input data to next export function
          HeaderName: "" # Name of the header key to add to the HTTP header
          SecretValueKey: "" # Name of the secret for the header value in the SecretStore
          SecretName: "" # Path to the secret for the header value in the SecretStore

  InsecureSecrets:
    http:
      SecretName: "http"
      SecretData:
        headervalue: "<put your value here>"
    aes:
      SecretName: "aes"
      SecretData:
        key: "217A24432646294A404E635266556A586E3272357538782F413F442A472D4B6150645367566B59703373367639792442264529482B4D6251655468576D5A7134"

Service:
  Host: "localhost"
  Port: 59704
  StartupMsg: "app-http-export has Started"

MessageBus:
  Optional:
    ClientId: "app-http-export"

# Using default Trigger config from common config