[Writable]
  LogLevel = "INFO"

  [Writable.Pipeline]
  TargetType = "metric"
  ExecutionOrder = "ToLineProtocol, Batch, HTTPExport"

  [Writable.Pipeline.Functions]
    [Writable.Pipeline.Functions.ToLineProtocol]
      [Writable.Pipeline.Functions.ToLineProtocol.Parameters]
      Tags = "" # optional comma separated list of additional tags to add to the metric in to form "tag:value,..."
    [Writable.Pipeline.Functions.Batch]
      [Writable.Pipeline.Functions.Batch.Parameters]
      Mode = "bytimecount" # can be "bycount", "bytime" or "bytimecount"
      BatchThreshold = "100"
      TimeInterval = "60s"
      MergeOnSend = "true"
    [Writable.Pipeline.Functions.HTTPExport]
      [Writable.Pipeline.Functions.HTTPExport.Parameters]
      Method = "post"
      MimeType = "raw"
      Url = "http:/<your-influxdb-host>:8086/api/v2/write?org=<your-org>&bucket=<your-bucket>&precision=ns"
      HeaderName = "authorization" # Name of the header key to add to the HTTP header
      SecretValueKey = "token" # Name of the secret for the header value in the SecretStore
      SecretName = "influxdb" # Path to the secret for the header value in the SecretStore

  [Writable.InsecureSecrets]
    [Writable.InsecureSecrets.influxdb]
    SecretName = "influxdb"
      [Writable.InsecureSecrets.influxdb.SecretData]
      token = "Token <place InfluxDB token here>"

  [Writable.Telemetry]
  Interval = "0s" # Don't report any metrics as that would be cyclic with this profiles' processing.

[Service]
Port = 59707
StartupMsg = "app-metrics-influxdb has Started"

[MessageBus]
  [MessageBus.Optional]
  # Default MQTT Specific options that need to be here to enable evnironment variable overrides of them
  ClientId ="app-metrics-influxdb"

[Trigger]
# Note that the MessageBus connection above is used by edgex-messagebus trigger which is the default set in common config
SubscribeTopics = "telemetry/#" # Base topic is prepened to this topic when using edgex-messagebus
