name: edgex-app-service-configurable
base: core22
license: Apache-2.0
summary: EdgeX App Service Configurable application service
description: Refer to https://snapcraft.io/edgex-app-service-configurable
adopt-info: app-service-config

architectures:
  - build-on: amd64
  - build-on: arm64

grade: stable
confinement: strict

# 1: edinburgh
# 2: fuji
# 3: geneva, hanoi
# 4: ireland, jakarta, kamakura, levski
# 5: minnesota
epoch: 5

slots:
  edgex-secretstore-token:
    interface: content
    source:
      write: 
        - $SNAP_DATA/app-http-export
        - $SNAP_DATA/app-mqtt-export
        - $SNAP_DATA/app-external-mqtt-trigger
        - $SNAP_DATA/app-functional-tests
        - $SNAP_DATA/app-push-to-core
        - $SNAP_DATA/app-rules-engine
plugs:
  app-service-configurable-config:
    interface: content
    target: $SNAP_DATA/config

apps:
  app-service-configurable:
    command: bin/service-wrapper.sh
    command-chain:
      - bin/source-env-file.sh
    daemon: simple
    install-mode: disable
    plugs: [network, network-bind]

parts:
  app-service-config:
    source: .
    plugin: make
    build-packages: 
      - git
    build-snaps:
      - go/1.20/stable
    override-build: |
      cd $CRAFT_PART_SRC

      if git describe ; then
        VERSION=$(git describe --tags --abbrev=0 | sed 's/v//')
      else
        VERSION="0.0.0"
      fi

      # set the version of the snap
      craftctl set version=$VERSION

      # write version to file for the build
      echo $VERSION > VERSION

      make build
      install -DT "./app-service-configurable" "$CRAFT_PART_INSTALL/bin/app-service-configurable"

      RES=$CRAFT_PART_INSTALL/config/res
      mkdir -p $RES
      cp -r res/* $RES
      
      DOC=$CRAFT_PART_INSTALL/usr/share/doc/app-service-configurable
      mkdir -p $DOC
      cp Attribution.txt $DOC/Attribution.txt
      cp LICENSE $DOC/LICENSE

  local-bin:
    plugin: dump
    source: snap/local/bin
    organize:
      source-env-file.sh: bin/source-env-file.sh
      service-wrapper.sh: bin/service-wrapper.sh

  helper-go:
    source: snap/local/helper-go
    plugin: make
    build-snaps:
      - go/1.20/stable
    override-build: |
      cd $CRAFT_PART_SRC
      make build
      install -DT ./helper-go $CRAFT_PART_INSTALL/bin/helper-go
