name: edgex-app-service-configurable
base: core20
license: Apache-2.0
adopt-info: metadata

architectures:
  - build-on: amd64
  - build-on: arm64

grade: stable
confinement: strict

# 1: edinburgh
# 2: fuji
# 3: geneva, hanoi
# 4: ireland, jakarta
epoch: 4

slots:
  edgex-secretstore-token:
    interface: content
    source:
      write: 
        - $SNAP_DATA/app-http-export
        - $SNAP_DATA/app-mqtt-export
        - $SNAP_DATA/app-external-mqtt-trigger
        - $SNAP_DATA/app-functional-tests
        - $SNAP_DATA/app-push-to-core
        - $SNAP_DATA/app-rules-engine
plugs:
  app-service-configurable-config:
    interface: content
    target: $SNAP_DATA/config

  # deprecated
  app-config:
    interface: content
    target: $SNAP_DATA/config

apps:
  app-service-configurable:
    adapter: full
    command: bin/service-wrapper.sh
    command-chain:
      - bin/source-env-file.sh
    daemon: simple
    install-mode: disable
    plugs: [network, network-bind]

parts:
  app-service-config:
    after: [metadata]
    source: .
    plugin: make
    build-packages: [gcc, git, pkg-config]
    build-snaps:
      - go/1.20/stable
    override-build: |
      cd $SNAPCRAFT_PART_SRC

      # the version is needed for the build
      cat ./VERSION

      make tidy
      make build

      install -DT "./app-service-configurable" "$SNAPCRAFT_PART_INSTALL/bin/app-service-configurable"

      RES=$SNAPCRAFT_PART_INSTALL/config
      mkdir -p $RES
      cp -r res $RES
      
      DOC=$SNAPCRAFT_PART_INSTALL/usr/share/doc/app-service-configurable
      mkdir -p $DOC
      cp Attribution.txt $DOC/Attribution.txt
      cp LICENSE $DOC/LICENSE

  local-bin:
    plugin: dump
    source: snap/local/bin
    organize:
      source-env-file.sh: bin/source-env-file.sh
      service-wrapper.sh: bin/service-wrapper.sh

  metadata:
    plugin: nil
    source: https://github.com/canonical/edgex-snap-metadata.git
    source-branch: appstream
    source-depth: 1
    override-build: |
      # install the icon at the default internal path
      install -DT edgex-snap-icon.png \
        $SNAPCRAFT_PART_INSTALL/meta/gui/icon.png      

      # change to this project's repo to get the version
      cd $SNAPCRAFT_PROJECT_DIR

      if git describe ; then
        VERSION=$(git describe --tags --abbrev=0 | sed 's/v//')
      else
        VERSION="0.0.0"
      fi
      
      # write version to file for the build
      echo $VERSION > ./VERSION

      # set the version of this snap
      snapcraftctl set-version $VERSION
    parse-info: [edgex-app-service-configurable.metainfo.xml]

  helper-go:
    source: snap/local/helper-go
    plugin: make
    build-snaps:
      - go/1.20/stable
    override-build: |
      cd $SNAPCRAFT_PART_SRC
      make build
      install -DT ./helper-go $SNAPCRAFT_PART_INSTALL/bin/helper-go
