Writable:
  LogLevel: "INFO"
  StoreAndForward: 
    Enabled: false

  Pipeline:
    ExecutionOrder: "MQTTExport"
    TargetType: "raw"

    Functions:
      MQTTExport:
        Parameters:
          BrokerAddress: "tcp://localhost:1883" # Hive Public Test Broker
          # Topic can have placeholders in the form "{key-name}" that are replaced with matching Context values. Error occurs if no value match place holder(s).
          Topic: "edgex-export"
          SecretName: "mqtt"
          ClientId: "external-mqtt-export"
          QOS: "0"
          AutoReconnect: "false"
          KeepAlive: "" # Empty indicates to use default value
          ConnectTimeout: "" # Empty indicates to use default value
          Retain: "false"
          SkipVerify: "false"
          AuthMode: "none"
          PersistOnError: "false"

  # Metrics can only be reported when the MessageBus (below) is enabled.
  Telemetry:
    Interval: "0s" # Disables reporting

  InsecureSecrets:
    mqtt:
      SecretName: "mqtt"
      SecretData:
        username: ""
        password: ""
        cacert: ""
        clientcert: ""
        clientkey: ""

Service:
  Host: "localhost"
  Port: 59706
  StartupMsg: "app-external-mqtt-trigger has Started"

MessageBus:
  Disabled: true  # Set to false when collecting metrics

Trigger:
  Type: "external-mqtt"
  SubscribeTopics: "external-request/#"
  PublishTopic: "" # optional if publishing response back to the the External MQTT Broker
  ExternalMqtt:
    Url: "tcp://localhost:1883" #  fully qualified URL to connect to the MQTT broker
    ClientId: "external-mqtt-trigger"
    ConnectTimeout: "5s" # 5 seconds
    AutoReconnect: true
    KeepAlive: 10 # Seconds (must be 2 or greater)
    QoS: 0 # Quality of Service 0 (At most once), 1 (At least once) or 2 (Exactly once)
    Retain: true
    SkipCertVerify: false
    SecretName: "mqtt" 
    AuthMode: "none"
    Will:
      Enabled: false
      Payload: ""
      Qos: 0
      Retained: false
      Topic: ""