[Writable]
LogLevel = "INFO"

  [Writable.Pipeline]
  ExecutionOrder = "MQTTExport"
  TargetType = "raw"

  [Writable.Pipeline.Functions]
    [Writable.Pipeline.Functions.MQTTExport]
      [Writable.Pipeline.Functions.MQTTExport.Parameters]
      BrokerAddress = "tcp://localhost:1883" # Hive Public Test Broker
      # Topic can have place holders in the form "{key-name}" that are replaced with matching Context values. Error occurs if no value match place holder(s).
      Topic = "edgex-export"
      SecretName = "mqtt"
      ClientId = "external-mqtt-export"
      QOS="0"
      AutoReconnect="false"
      KeepAlive = "" # Empty indicates to use default value
      ConnectTimeout = "" # Empty indicates to use default value
      Retain="false"
      SkipVerify = "false"
      AuthMode = "none"
      PersistOnError = "false"

  # Reporting metrics requires the "edgex-messagebus" Trigger.
  # Since this profile uses "external-mqtt" trigger the metrics can not be reported.
  [Writable.Telemetry]
  Interval = "0s" # Disables reporting

[Service]
Port = 59706
StartupMsg = "app-external-mqtt-trigger has Started"

[MessageBus]
Disabled = true

[Trigger]
Type="external-mqtt"
SubscribeTopics="external-request/#"
PublishTopic="" # optional if publishing response back to the the External MQTT Broker
  [Trigger.ExternalMqtt]
    Url = "tcp://localhost:1883" #  fully qualified URL to connect to the MQTT broker
    ClientId = "external-mqtt-trigger"
    ConnectTimeout = "5s" # 5 seconds
    AutoReconnect = true
    KeepAlive = 10 # Seconds (must be 2 or greater)
    QoS = 0 # Quality of Service 0 (At most once), 1 (At least once) or 2 (Exactly once)
    Retain = true
    SkipCertVerify = false
    SecretName = "mqtt-trigger" 
    AuthMode = "none"
